image:
  name: adambray/matcha-ice-cream
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - test

variables:
  MYSQL_DATABASE: home_dashboard
  MYSQL_PASSWORD: test
  MYSQL_USER: test
  MYSQL_ROOT_PASSWORD: test

test:
  stage: test
  script: pipeline/gitlab_ci_test.sh

